name: retinal-rl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.2
  - farama-notifications=0.0.4
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jax-jumpy=1.0.0
  - joblib=1.4.0
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - networkx
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - opentsne=1.0.1
  - pcre2=10.42
  - pillow=10.3.0
  - pip=23.3.1
  - ply=3.11
  - pybind11-abi=4
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-tzdata=2023.3
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2024.1
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.3.3
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - captum==0.7.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.10
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - faster-fifo==1.4.5
      - filelock==3.14.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.63.0
      - gymnasium==0.29.1
      - huggingface-hub==0.23.0
      - hydra-core
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markdown==3.6
      - markupsafe==2.1.5
      - num2words==0.5.13
      - omgifol==0.5.1
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pandas==2.2.2
      - protobuf==4.25.3
      - psutil==5.9.8
      - pygame==2.5.2
      - pyglet==2.0.15
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - git+https://github.com/alex-petrenko/sample-factory.git@071574b65d736efda4ce4de1caa8e140ae917c38#egg=sample-factory
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - signal-slot-mp==1.0.5
      - smmap==5.0.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torchscan==0.1.2
      - torchinfo
      - tqdm==4.66.4
      - tzdata==2024.1
      - vizdoom==1.2.3
      - wandb==0.16.6
      - werkzeug==3.0.3
