classification:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  objectives:
    - _target_: retinal_rl.classification.objective.ClassificationObjective
      weight: 1
    - _target_: retinal_rl.classification.objective.PercentCorrect
      weight: 0
  target_circuits:
    - cnn_encoder1
    - decoder
    - cnn_encoder2
    - fc_feedforward
    - classifier
