reconstruction:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003
  objectives:
    - _target_: retinal_rl.models.objective.ReconstructionLoss
      weight: 1
  target_circuits:
    - cnn_encoder1
    - cnn_encoder2
    - fc_feedforward
    - classifier
    - decoder
