# wandb sweep
description: Comparing autoencoders where the decoding happens before or after the FC layer.
program: main.py
method: grid
project: retinal-rl

parameters:
  optimizer:
    values: ['specialized', 'classification', 'reconstruction']
  brain:
    value: 'specialized-cnn-decoder'
