name: Scan Configs
on: [pull_request,workflow_dispatch]

env:
  singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
  sif_file: retinal-rl_singularity-image-latest.sif

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/setup.yml
      with:
        singularity_image: ${{ env.singularity_image }}

    - name: Scan classification config
      run: singularity exec ${{ env.sif_file }} python main.py -m +experiment=cifar10-class-recon command=scan system.device=cpu