name: Scan Configs
on: [push, pull_request]
jobs:
  scan:
    uses: ./.github/workflows/singularity_pull.yml
    with:
      singularity_image: oras://ghcr.io/berenslab/retinal-rl:singularity-image-latest
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}